// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OuderraadWielewaal.Data;

#nullable disable

namespace OuderraadWielewaal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313084315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OuderraadWielewaal.Models.Bestellijn", b =>
                {
                    b.Property<int>("BestellingId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Hoeveelheid")
                        .HasColumnType("int");

                    b.HasKey("BestellingId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Bestellijnen");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Bestelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BetaalStatus")
                        .HasColumnType("int");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int");

                    b.Property<string>("MolliePaymentId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TijdstipBesteld")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId");

                    b.ToTable("Bestellingen");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("TijdstipGeactiveerd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UniekeCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("WachtwoordHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Gebruikers");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Producten");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        });
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Productdetail", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tijdstip")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<float>("Prijs")
                        .HasColumnType("float");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "Tijdstip");

                    b.ToTable("Productdetails");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Tijdstip = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Naam = "Cola",
                            Prijs = 2.5f,
                            ProductType = 0
                        },
                        new
                        {
                            ProductId = 2,
                            Tijdstip = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Naam = "Chips Paprika",
                            Prijs = 2f,
                            ProductType = 1
                        });
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Rollen");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Roltoewijzing", b =>
                {
                    b.Property<int>("GebruikerId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("GebruikerId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("Roltoewijzingen");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Tafel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nummer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tafels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nummer = 1
                        },
                        new
                        {
                            Id = 2,
                            Nummer = 2
                        },
                        new
                        {
                            Id = 3,
                            Nummer = 3
                        });
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Tafeltoewijzing", b =>
                {
                    b.Property<int>("GebruikerId")
                        .HasColumnType("int");

                    b.Property<int>("TafelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TijdstipToegewezen")
                        .HasColumnType("datetime(6)");

                    b.HasKey("GebruikerId", "TafelId", "TijdstipToegewezen");

                    b.HasIndex("TafelId");

                    b.ToTable("Tafeltoewijzingen");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Bestellijn", b =>
                {
                    b.HasOne("OuderraadWielewaal.Models.Bestelling", "Bestelling")
                        .WithMany("Bestellijnen")
                        .HasForeignKey("BestellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OuderraadWielewaal.Models.Product", "Product")
                        .WithMany("Bestellijnen")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bestelling");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Bestelling", b =>
                {
                    b.HasOne("OuderraadWielewaal.Models.Gebruiker", "Gebruiker")
                        .WithMany("Bestellingen")
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Productdetail", b =>
                {
                    b.HasOne("OuderraadWielewaal.Models.Product", "Product")
                        .WithMany("Productdetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Roltoewijzing", b =>
                {
                    b.HasOne("OuderraadWielewaal.Models.Gebruiker", "Gebruiker")
                        .WithMany("Roltoewijzingen")
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OuderraadWielewaal.Models.Rol", "Rol")
                        .WithMany("Roltoewijzingen")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruiker");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Tafeltoewijzing", b =>
                {
                    b.HasOne("OuderraadWielewaal.Models.Gebruiker", "Gebruiker")
                        .WithMany("Tafeltoewijzingen")
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OuderraadWielewaal.Models.Tafel", "Tafel")
                        .WithMany("Tafeltoewijzingen")
                        .HasForeignKey("TafelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruiker");

                    b.Navigation("Tafel");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Bestelling", b =>
                {
                    b.Navigation("Bestellijnen");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Gebruiker", b =>
                {
                    b.Navigation("Bestellingen");

                    b.Navigation("Roltoewijzingen");

                    b.Navigation("Tafeltoewijzingen");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Product", b =>
                {
                    b.Navigation("Bestellijnen");

                    b.Navigation("Productdetails");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Rol", b =>
                {
                    b.Navigation("Roltoewijzingen");
                });

            modelBuilder.Entity("OuderraadWielewaal.Models.Tafel", b =>
                {
                    b.Navigation("Tafeltoewijzingen");
                });
#pragma warning restore 612, 618
        }
    }
}
